const paths2 = [
  { path: '/', forbiddenWord: '' },
  { path: '/markets', forbiddenWord: '' },
  { path: '/mobility', forbiddenWord: 'markets' },
  { path: '/aeronautics', forbiddenWord: '' },
  { path: '/space', forbiddenWord: '' },
  { path: '/others', forbiddenWord: '' },
  { path: '/products-mobility', forbiddenWord: 'products-aeronautics' },
  { path: '/products-aeronautics', forbiddenWord: 'products-space' },
  { path: '/products-space', forbiddenWord: 'products-others' },
  { path: '/products-others', forbiddenWord: '' },
  { path: '/about-us', forbiddenWord: '' },
  { path: '/colab-s2ul', forbiddenWord: '' },
  { path: '/news', forbiddenWord: '' },
  { path: '/news/engineering-creativity-25', forbiddenWord: '' },
  { path: '/news/cti-aeroespacial-is-present-in-the-laad2025', forbiddenWord: '' },
  { path: '/news/mh-1-first-year-in-space', forbiddenWord: '' },
  { path: '/partners', forbiddenWord: '' },
  { path: '/quality-certification', forbiddenWord: '' },
  { path: '/expertise-facilities', forbiddenWord: '' },
  { path: '/careers', forbiddenWord: '' },
  { path: '/contacts', forbiddenWord: '' },
  { path: '/projects', forbiddenWord: '' },
  { path: '/suppliers', forbiddenWord: '' },
  { path: '/privacy', forbiddenWord: '' },
  { path: '/terms', forbiddenWord: '' },
  { path: '/cookies', forbiddenWord: '' }
];

const paths = [
  '/',
  '/markets',
  '/mobility',
  '/aeronautics',
  '/space',
  '/others',
  '/products-mobility',
  '/products-aeronautics',
  '/products-space',
  '/products-others',
  '/about-us',
  '/colab-s2ul',
  '/news',
  '/news/engineering-creativity-25',
  '/news/cti-aeroespacial-is-present-in-the-laad2025',
  '/news/mh-1-first-year-in-space',
  '/news/new-times-new-challenges-competitiveness',
  '/news/atlantic-constellation',
  '/news/northern-portugal-signs-agreement-with-rondonia-to-develop-carbon-certification',
  '/news/mission-on-board-the-d-carlos',
  '/news/lus222-continues-its-journey',
  '/news/kc-390s-first-flight-anniversary',
  '/news/ceiia-at-the-17th-european-space-conference-in-brussels',
  '/news/ceiia-was-recognized-as-game-changer',
  '/news/be-neutral-demo-day',
  '/news/eliot-is-going-to-shorten-distances-to-save-lives',
  '/news/international-astronautical-congress-iac',
  '/news/norte-surf-fest',
  '/news/boil-festival',
  '/news/launch-of-cti-aeroespacial',
  '/news/apm-at-paris',
  '/news/toyota-apm-enters-production',
  '/news/ayr-id-wins-innovation-award',
  '/news/portugal-receives-the-first-kc-390-from-embraer',
  '/news/demonstration-vehicle-of-our-fly-pt-aam-mobility-concept',
  '/news/launch-of-our-mh-1-satellite-into-orbit',
  '/news/debut-of-the-atlantic-constellation',
  '/news/ceiia-delivers-two-seafloor-landers-to-the-portuguese-navy',
  '/news/creation-of-satellite-based-bathymetric-chart',
  '/news/launch-of-phisat-2-mission',
  '/news/preparing-future-astronauts-to-explore-the-moon-and-space',
  '/news/ceiia-and-rfa-portugal-send-rfa-one-rocket-structures-to-launch-site',
  '/news/science-2024-meeting',
  '/news/ayr-andfootball---inception-of-player-0',
  '/news/first-images-of-mh-1',
  '/partners',
  '/quality-certification',
  '/expertise-facilities',
  '/careers',
  '/contacts',
  '/projects',
  '/suppliers',
  '/privacy',
  '/terms',
  '/cookies'
];

const extraPaths = paths
  .filter(p => !paths2.some(obj => obj.path === p)) 
  .map(p => ({ path: p, forbiddenWord: '' }));

const allPaths = [...paths2, ...extraPaths];

module.exports = allPaths;
